
		.filename "virusGAME_sinO7"
		.page	1
		.size	32			;ROM de 32KB
		.ROM
		.BIOS


; VARIABLES DEL SISTEMA

CLIKSW		EQU	$F3DB

;CONTROL DE LAS INTERRUPCIONES

;HOOK		EQU	$FD9A



; AJUSTES INICIALES

SPOINT:		.search				;ROM de 32KB




;AJUSTES
		DI
		CALL PLAYER_OFF

; MUSICA DATOS INICIALES

LD	HL,BUFFER_CANAL_A	;RESERVAR MEMORIA PARA BUFFER DE SONIDO!!!!!
		LD	[CANAL_A],HL		;RECOMENDABLE $10 O MAS BYTES POR CANAL.

		LD	HL,BUFFER_CANAL_B
		LD	[CANAL_B],HL

		LD	HL,BUFFER_CANAL_C
		LD	[CANAL_C],HL

		LD	HL,BUFFER_CANAL_P
		LD	[CANAL_P],HL

		
		
	
				
		LD	A,0			;REPRODUCIR LA CANCION Nº 0
		CALL	CARGA_CANCION





;INICIA INTERRUPCIONES

		LD	HL,INICIO
		LD	[HOOK+1],HL
		LD	A,$C3
		LD	[HOOK],A
		EI
		LD	A,$0E
		LD	[PSG_REG+13],A


		
		LD HL, SONIDO0
		LD [PUNTERO_SONIDO],HL
		LD      HL,INTERR       ;CARGA CANCION
		SET     2,[HL] 
LOOP:	

CHECK_KEY:		
		XOR   a
		CALL  GTSTCK
		CP    0
		JP    z, LOOP
		CP    1 ;UP
		JP    z, TRATE_SOUND_0
		;2->UP_RIGHT
		CP    3 ;RIGHT
		JP    z, TRATE_SOUND_1
		;4->DOWN_RIGHT
		;5->DOWN
		;....
		JP	LOOP
	
TRATE_SOUND_0:	
		LD    HL, SONIDO0            ;DIRECCION DEL EFECTO QUE TIENE QUE SONAR
		JP    CONTINUE_TRATING_SOUND

TRATE_SOUND_1:	
		LD    HL, SONIDO1            ;DIRECCION DEL EFECTO QUE TIENE QUE SONAR
		JP    CONTINUE_TRATING_SOUND

CONTINUE_TRATING_SOUND:		
		LD    [PUNTERO_SONIDO],HL
		LD    HL,INTERR       ;ACTIVA EFECTO
		SET   2,[HL] 
		JP    LOOP
		
;archivo de instrumentos


.INCLUDE	"virusGAME_sinO7.MUS.asm"


SONG_0:		.INCBIN	"virusGAME_sinO7.MUS" ;

TABLA_SONG:	DW	SONG_0 ;SONG_1

;código del player

.INCLUDE	"WYZProplay47cMSX_JVWYZ.asm"

TAM_CANAL	EQU $40
BUFFER_CANAL_A EQU	INTERR+$100
BUFFER_CANAL_B EQU	BUFFER_CANAL_A+TAM_CANAL
BUFFER_CANAL_C EQU	BUFFER_CANAL_B+TAM_CANAL
BUFFER_CANAL_P EQU	BUFFER_CANAL_C+TAM_CANAL



;variables del player

;.INCLUDE	"WYZProplay47c_RAM.asm"
