		MODULE		MWORK

;============================================
; CONSTANTS
;============================================
K_MAX_NUMBER_OF_SPRITES         EQU 13
K_EOF				EQU 254	
K_NORMAL_SHOOT                  EQU 0
K_DOUBLE_SHOOT                  EQU 1
K_TRIPLE_SHOOT                  EQU 3
K_START_LEVEL 			EQU 1			; 1 BASED
K_START_MAP 			EQU K_START_LEVEL-1	; 0 BASED
K_MAX_BULLETS_COUNT		EQU 24
K_INITIAL_PLAYER_LIVES		EQU 10
K_MAX_NUMBER_OF_ZOMBIES		EQU 10
K_MAX_NUMBER_OF_FIXED_INDESTRUCTIBLES EQU 4+1+4		
K_MAX_NUMBER_OF_SHOOTS		EQU 4
K_DATA_PER_ENTITY		EQU 14			
K_MAX_NUMBER_OF_INDESTRUCTIBLES EQU K_MAX_NUMBER_OF_FIXED_INDESTRUCTIBLES+K_MAX_NUMBER_OF_SHOOTS							
K_ENTITIES_LENGTH 		EQU K_MAX_NUMBER_OF_ZOMBIES+K_MAX_NUMBER_OF_INDESTRUCTIBLES							
K_ZOMBIES_SPEED			EQU 12
;============================================
; MUSIC VARS
;============================================
BUFF_CANAL_A			#16
BUFF_CANAL_B			#16    
BUFF_CANAL_C			#16
BUFF_CANAL_P			#16
INTERR				#(150+32)


;============================================
; GAME VARS
;============================================
ANIMATION_TICK		#1				; CLOCK FOR ANIMATIONS AND RANDOM NUMBERS
ZOMBIES_ANIMATION_TICK	#1
ZOMBIES_SPEED		#1
NUM_OF_CONTINUES	#1
ALREADY_CONTINUE	#1				; IF HAS CONTINUED DON'T SHOW LAST INTERMISSION OR HALF PATH SCREEN
PLAYER_SHOOT_TYPE       #1                              ; K_NORMAL_SHOOT, K_DOUBLE_SHOOT, K_TRIPLE_SHOOT
PLAYER_SHOOT_COST       #1
KEY_PRESSED             #1                              ; 0 NO, 1 YES
RUN_NUMBER              #1                              ; 0 FIRST RUN, 1 SECOND RUN
CURRENT_NUMBER_OF_SHOOTS #1                             
PLAYER_POINTS           #3                              
HI_SCORE		#3
TICK_REFRESH		#1
LEVEL			#1
PLAYER_BULLETS		#1
PLAYER_SHOOT_WAIT	#1  				; COUNTER TO ALLOW OTHER SHOOT
CHARGE_BULLETS_COUNTER	#1
CURRENT_NUMBER_OF_ZOMBIES #1
PRE_GAME_OVER		#1
SURVIVORS_TO_SAVE	#1
CURRENT_ZOMBIE_TYPE	#1
SHOOTS_TO_KILL_ZOMBIE	#1	
COUNT_DOWN		#4 
CURRENT_SONG		#1


;===========================================
; PLAYER VARS
;===========================================
PLAYER_KEY_PRESSED 	#1
PLAYER_SPACE_KEY_PRESSED #1  				; TO CONTROL SHOOT
PLAYER_LIVES		#1
PLAYER_IMMUNITY		#1
PLAYER_Y 		#1
PLAYER_X 		#1	
PLAYER_DIRECTION	#1				; LIKE JOYSTICK CODES
PLAYER_PREVIOUS_Y	#1				; TO UNDO MOVEMENT
PLAYER_PREVIOUS_X	#1
   



;============================================
; FUNCTION PARAMETERS AND LOCAL VARS
;============================================
ENTITY_EXIT		#1
ENTITY_EXIT_MAP_Y	#1
ENTITY_EXIT_MAP_X	#1

 ;CanGo
PARAM_CAN_GO_Y          #1
PARAM_CAN_GO_X		#1

CHECK_COLISION_POS	#2

TMP_Y			#1
TMP_X			#1

TRATE_ZOMBIE_PREV_POS   #2
TRATE_ZOMBIE_FIRST_OPTION #1



;============================================
; SCREEN VARS
;============================================
CAMERA_SCREEN           #(32*24)                        
CAMERA_OFFSET           #2                              ; TOP-LEFT CORNER ADDRESS OF THE CAMERA IN THE MAP
CAMERA_CHANGED		#1
INTER_SCROLL_COUNTER_X	#1			 	; CONTROL THE 8PX HORIZONTAL SCROLL
INTER_SCROLL_COUNTER_Y	#1				; CONTROL THE 8PX VERTICAL SCROLL
CAMERA_TILE_Y_TOP    	#1				; TOP CAMERA POSITION IN TILED MAP
CAMERA_TILE_X_LEFT	#1
CAMERA_TILE_Y_DOWN	#1
CAMERA_TILE_X_RIGHT	#1
PLAYER_PATTERN		#2

TMP_COUNTER             #2
TMP_UNZIP		#(32*8*8)


;============================================
; OPERATION VARS
;============================================
CURRENT_SPRITES_TABLE   #2
CURRENT_SPRITES_TABLE_POSITION #2

SPRITES_TABLE		#0
SPRITES_TABLE_0         #4
SPRITES_TABLE_1         #4
SPRITES_TABLE_2         #4
SPRITES_TABLE_3         #4
SPRITES_TABLE_4         #4
SPRITES_TABLE_5         #4
SPRITES_TABLE_6         #4
SPRITES_TABLE_7         #4
SPRITES_TABLE_8         #4
SPRITES_TABLE_9         #4
SPRITES_TABLE_10        #4
SPRITES_TABLE_11        #4

LIST_ENTITIES_DATA			#0
LIST_DESTRUCTIBLE_ENTITIES_DATA		#(K_MAX_NUMBER_OF_ZOMBIES*K_DATA_PER_ENTITY)
LIST_INDESTRUCTIBLE_ENTITIES_DATA	#(K_MAX_NUMBER_OF_FIXED_INDESTRUCTIBLES*K_DATA_PER_ENTITY)
LIST_SHOOTS				#(K_MAX_NUMBER_OF_SHOOTS*K_DATA_PER_ENTITY)
LIST_ENTITIES_DATA_END			#1


THE_MAP                 #(64*32)

		ENDMODULE